OnlineShopCore/Models/HomeViewModel.cs
using OnlineShopCore.Application.ViewModels.Product;
using OnlineShopCore.Application.ViewModels.Utilities;
using System.Collections.Generic;

namespace OnlineShopCore.Models
{
    public class HomeViewModel
    {

        public IEnumerable<SlideViewModel> Slides { get; set; }
        public IEnumerable<ProductViewModel> LastestProducts { get; set; }
        public IEnumerable<ProductViewModel> HotProducts { get; set; }
        public IEnumerable<ProductViewModel> TopSellProducts { get; set; }
        public IEnumerable<PromotionViewModel> Promotions { get; set; }

    }
}

OnlineShopCore/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineShopCore.Application.Dapper.Intefaces;
using OnlineShopCore.Extensions;
using System.Threading.Tasks;

namespace OnlineShopCore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Staff,Admin")]
    public class HomeController : BaseController
    {
        private readonly IReportService _reportService;
        private readonly IUserReportService _userReportService;
        private readonly IOrderReportService _orderReportService;
        private readonly ITopProductReportService _topProductReportService;
        public HomeController(IReportService reportService, ITopProductReportService topProductReportService,
            IUserReportService userReportService, IOrderReportService orderReportService)
        {
            _reportService = reportService;
            _userReportService = userReportService;
            _orderReportService = orderReportService;
            _topProductReportService = topProductReportService;
        }
        public IActionResult Index()
        {
            var email = User.GetSpecificClaim("Email");

            return View();
        }

        public async Task<IActionResult> GetRevenue(string fromDate, string toDate)
        {
            return new OkObjectResult(await _reportService.GetReport(fromDate, toDate));
        }

        public async Task<IActionResult> GetNewUser(string fromDate, string toDate)
        {
            return new OkObjectResult(await _userReportService.GetReport(fromDate, toDate));
        }

        public async Task<IActionResult> GetNewOrder(string fromDate, string toDate)
        {
            return new OkObjectResult(await _orderReportService.GetReport(fromDate, toDate));
        }

        public async Task<IActionResult> GetTopVisitProduct()
        {
            return new OkObjectResult(await _topProductReportService.GetReport());
        }
    }
}

OnlineShopCore/Controllers/Components/BlogsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace OnlineShopCore.Controllers.Components
{
    public class BlogsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

OnlineShopCore/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using OnlineShopCore.Application.Interfaces;
using OnlineShopCore.Models;
using OnlineShopCore.Services;
using OnlineShopCore.Utilities.Constants;
using System.Threading.Tasks;

namespace OnlineShopCore.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        private readonly IFeedbackService _feedbackService;
        private readonly IEmailSender _emailSender;
        private readonly IConfiguration _configuration;
        private readonly IViewRenderService _viewRenderService;

        public ContactController(IContactService contactSerivce,
            IViewRenderService viewRenderService,
            IConfiguration configuration,
            IEmailSender emailSender, IFeedbackService feedbackService)
        {
            _contactService = contactSerivce;
            _feedbackService = feedbackService;
            _emailSender = emailSender;
            _configuration = configuration;
            _viewRenderService = viewRenderService;
        }

        [Route("contact")]
        [HttpGet]
        public IActionResult Index()
        {
            var contact = _contactService.GetById(CommonConstants.DefaultContactId);
            var model = new ContactPageViewModel { Contact = contact };
            return View(model);
        }

        [Route("contact")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Index(ContactPageViewModel model)
        {
            if (ModelState.IsValid)
            {
                _feedbackService.Add(model.Feedback);
                _feedbackService.SaveChanges();
                var content = await _viewRenderService.RenderToStringAsync("Contact/_ContactMail", model.Feedback);
                await _emailSender.SendEmailAsync(_configuration["MailSettings:AdminMail"], "Have new contact feedback", content);
                ViewData["Success"] = true;
            }

            model.Contact = _contactService.GetById("default");

            return View("Index", model);
        }
    }
}

OnlineShopCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using OnlineShopCore.Application.Interfaces;
using OnlineShopCore.Models;
using System;
using System.Diagnostics;

namespace OnlineShopCore.Controllers
{
    public class HomeController : Controller
    {
        private IProductService _productService;
        private ISlideService _slideService;
        private readonly IStringLocalizer<HomeController> _localizer;

        public HomeController(IProductService productService, ISlideService slideService,
            IStringLocalizer<HomeController> localizer)
        {
            _productService = productService;
            _slideService = slideService;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            var title = _localizer["Title"];
            var culture = HttpContext.Features.Get<IRequestCultureFeature>().RequestCulture.Culture.Name;
            var homeVm = new HomeViewModel();
            homeVm.Slides = _slideService.GetSlide();
            homeVm.LastestProducts = _productService.GetLastest(16);
            homeVm.HotProducts = _productService.GetHotProduct(16);
            homeVm.TopSellProducts = _productService.GetHomeProduct(16);
            homeVm.Promotions = _productService.GetPromotion();

            return View(homeVm);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

OnlineShopCore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

OnlineShopCore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineShopCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model HomeViewModel
@section Scripts{
    <script>
        $(".js-select2").each(function () {
            $(this).select2({
                minimumResultsForSearch: 20,
                dropdownParent: $(this).next('.dropDownSelect2')
            });
        })

        $('.parallax100').parallax100();

        $('.gallery-lb').each(function () { // the containers for all your galleries
            $(this).magnificPopup({
                delegate: 'a', // the selector for gallery item
                type: 'image',
                gallery: {
                    enabled: true
                },
                mainClass: 'mfp-fade'
            });
        });

        $('.js-addwish-b2').on('click', function (e) {
            e.preventDefault();
        });

        $('.js-addwish-b2').each(function () {
            var nameProduct = $(this).parent().parent().find('.js-name-b2').html();
            $(this).on('click', function () {
                swal(nameProduct, "is added to wishlist !", "success");

                $(this).addClass('js-addedwish-b2');
                $(this).off('click');
            });
        });

        $('.js-addwish-detail').each(function () {
            var nameProduct = $(this).parent().parent().parent().find('.js-name-detail').html();

            $(this).on('click', function () {
                swal(nameProduct, "is added to wishlist !", "success");

                $(this).addClass('js-addedwish-detail');
                $(this).off('click');
            });
        });

        /*---------------------------------------------*/

        $('.js-addcart-detail').each(function () {
            var nameProduct = $(this).parent().parent().parent().parent().find('.js-name-detail').html();
            $(this).on('click', function () {
                swal(nameProduct, "is added to cart !", "success");
            });
        });

        $('.js-pscroll').each(function () {
            $(this).css('position', 'relative');
            $(this).css('overflow', 'hidden');
            var ps = new PerfectScrollbar(this, {
                wheelSpeed: 1,
                scrollingThreshold: 1000,
                wheelPropagation: false,
            });

            $(window).on('resize', function () {
                ps.update();
            })
        });
    </script>
    
}

<!-- Slider -->
@await Component.InvokeAsync("Slider")

<!-- Banner -->
@await Component.InvokeAsync("Banner")

<!-- Store overview -->
@await Component.InvokeAsync("StoreOverview")

<!-- Promotion-->
@await Component.InvokeAsync("Promotion")

<!-- Blogs-->
@*@await Component.InvokeAsync("Blogs")*@